### PR TITLE
Laid out room size, and exits.

### PR DESCRIPTION
**Pull request by jcode89**
It is a fairly basic .csv file containing data relevant to the entire game. We can pull data out of the file easily if needed. It already has room sizes, exit locations and where the room is locked, but I am sure we could add items in the room, or even create a new file for that if needed.

### CODE REVIEW

**Comment by rubyyot** [comment]
I think that makes sense, using a coordinate system within the room.

**Comment by jcode89** [comment]
Yeah, I mean I really couldn't think of any other way to setup a board without getting into GUI programming, which is it's own separate beast.

**Comment by rubyyot** [comment]
The room could track the co-ordinates of player, items and locations within it. 

When two things are in the same cell (or adjacent?) they can interact.  Just an idea, doesn't have to be that way. 

did you ever play nethack?  You can watch or play a game here if you haven't... http://alt.org/nethack/soiled/

That is just one style of adventure game. There is also Zork which didn't have a map or rooms, but was path driven.  You can play online here:  http://textadventures.co.uk/games/view/5zyoqrsugeopel3ffhz_vq/zork

These are two entirely different approaches, both are valid options.  Of course you can do something different too.

**Comment by jcode89** [comment]
Tracking the player seems like a great idea. The methods so far in the room class just set up the rooms. I may change the class from `class Room():` to `class Room_Creator():` I believe access to the boards will still be available, or I could even make the next class a sub class of `class Room_Creator():`

**Comment by rubyyot** [comment]
RoomCreator could accept requests for rooms, create them and return Room instances

**Comment by rubyyot** [comment]
The Room would then be used to track locations within the room and draw the map of the stuff in the room

**Comment by rubyyot** [comment]
This is a tough feature with lots of choices. :)

**Comment by rubyyot** [comment]
Also I think that one of the issues you are running into is that this feature seems to be built on other features such as tiles that haven't been completed yet.  You might try working on issue #4 (Game setup: game map is composed of map tiles/spaces, and each tile has a set of coordinates #4) and once it is complete and merged, come back to this one.

**Comment by jcode89** [comment]
The code I was working on right now was more geared towards issue #11 (Game setup: write code to read text file and assign coordinates to map tiles according to location in "grid" of text file). The code reads the file and doesn't assign coordinates per se, but does create the board which is reall a set of coordinates.

**Comment by rubyyot** [comment]
Cool, we talked about this one and I figured out that I was confused.  I think this is good. :+1

**Comment by jcode89** [comment]
Awesome! At some point rebase will commence. 😁 The one change I might make is to the Exit column. I might make it Exit Row and Exit Column so that way the exits can be coordinates. 

Jonathan Colón

**Comment by rubyyot** [comment]
I think that is a change that is inevitable, so go for it

**Pull request merged**
