### PR TITLE
adds last two features. bacon. game end text.

### LINKED ISSUE #8: Game setup: make the end

### LINKED ISSUE #46: Game setup: add bacon prizes

### PR DESCRIPTION
**Pull request by phillipgray**
resolves #46.
resolves #8.

### CODE REVIEW

**Comment by degustaf** [comment]
Bacon does not show up in the map key.

**Comment by phillipgray** [comment]
@degustaf Good catch. Should be all set now.

**Comment by degustaf** [comment]
Yup, it's fixed.  I can't run the tests.  Do they all pass?

**Comment by phillipgray** [comment]
Kind of. There's one pesky level loader test that intermittently fails. It's a data structure problem in the hydrate method. Dictionaries are so fickle...

**Comment by degustaf** [comment]
Is it the test about the target of the roach?

**Comment by phillipgray** [comment]
yup. setting the roach target to the exit requires that the exit be unpacked from the json/dict before the roach in the list, which doesn't always happen, of course

**Comment by degustaf** [comment]
Looks good to me.

**Pull request merged**
