### PR TITLE
Items cannot be picked up if in bag.

### PR DESCRIPTION
**Pull request by jcode89**
Added code that stops the items from being added to the bag once they are in the bag. The character remains on the map, but I figured that is okay since in most games when you open the chest to gather the items the chest doesn't disappear.

### CODE REVIEW

**Comment by jamalhansen** [comment]
If you wanted to actually remove the item from the Room it would not be very difficult.   There is an add_item() method in Room() that adds an item to the Room().  You could make a remove_item() method that removes the item from Room.items and call it when it is picked up.   

Since the Room treats everything as an item you would probably want to add a concept of removability otherwise people could remove the exits or themselves. 

If you want to keep the implementation as is that is fine to.  It will make new rooms more difficult though.

**Comment by jcode89** [comment]
How would remove_items work? Wouldn't I have to modify build_map so that it feeds off of remove_item? Right now build_map seems to feed off of items.

**Comment by jamalhansen** [comment]
room has a list called items that contains everything in the room and is
used to draw the map too.  removing an item from that list removes it from
the room

**Comment by jcode89** [comment]
So theoretically speaking if I do `def remove_items(self, name):` and in this method is `self.items(x, y).remove(name)` all I would have to do is pass it the name argument and it would be removed from the list?

**Comment by jamalhansen** [comment]
lol. I think you just need to remove the key so something like 

def remove_items(self, name):
    if name in items.keys():
        items.pop(name, None)

**Comment by jamalhansen** [comment]
I really wish github didn't mess with Python's significant whitespace

**Comment by jcode89** [comment]
I thought items was a list :( Lol. I thought only dicts had keys

**Comment by jcode89** [comment]
@jamalhansen Just updating you. I get an AttributeError if I do `if name in self.items.key():` and I get a TypeError if I do `if name in self.items().keys():`

**Comment by jcode89** [comment]
Okay, so I am not sure what the problem is, but I am having tons of trouble taking the items off the map. pop didn't work because it needed an int not str, so I fixed it, and the item remained in the room. I tried the `.remove()` method to remove items from a list, that didn't work, I tried to `del self.items(x, y)[index]` and that didn't  work either. I think the problem is that I am removing items from a list in a method that items and build_map are not aware of, build_map still uses the list produced by items but the list in items is not recreated when remove_item is called. Basically you play the game and the methods all run, but build_map will always use the items method, and the list produced by items is unable to be changed from outside the `def items(self, x, y):` method. I mean you can "change" it but it won't effect build_map at all.

**Pull request merged**
