### PR TITLE
Created a super awesome Mary Poppins bag and TDD support

### PR DESCRIPTION
**Pull request by rubyyot**
I haven't yet done much here but wanted to try out the pull request process and get a little feedback.

I made my feature branch for my feature (18 - the Mary Poppins inventory bag) and made locations for unit and functional test code to live

functional_tests.py   <- functional tests
tests/<your unit test file.py>    <-unit tests

Does this work for everyone?  Am I using the pull request process correctly?

### CODE REVIEW

**Comment by rubyyot** [comment]
Ok, I've added some more functionality.  Now you can add() items, look() in bag, dump() bag into a dictionary and get counts.   Still need to handle removing items.   

The data structure that I'm using seems overly complex, a object (bag) wrapping a dict (items) whose values are dicts (metadata on items such as count and the item itself. 

I have followed a TDD workflow for this, but have backtracked in my design a couple times that left some artifacts such as dump() that I'm not sure if I should keep or remove.

I've pushed my latest code to this branch, comments are welcome. 

run functional tests with "python functional_tests.py"
run unit tests with "python -m unittest discover -s tests -p '*_test.py'"

also, the nosetests module can clean up that unittest command, but I didn't want to add modules to the project without getting buy in first.

**Comment by rubyyot** [comment]
So I'm getting pretty close to finishing this feature.. just need to wrap up this last functional test.   I think that I will leave dump() in there for now as it lends itself to adding persistence at some future point.  Also, it already has some tests.

**Comment by rubyyot** [comment]
Ok, feature is complete and all tests are passing.  Anyone who has any comments, please comment away!

**Comment by rubyyot** [comment]
All your re-BASS are belong to us!

I've found the re(bel)-base

**Comment by rubyyot** [comment]
Hey @rubyyot!  I think this is a great pull request, you should really rebase it an merge it into master.  That would really be swell

**Comment by rubyyot** [comment]
"This bag is something that I wish I had in real life" - Abraham Lincoln

"Mary Poppins would be jealous of this bag, git it rebased into master!" - Julie Andrews

**Comment by jcode89** [comment]
From what you demonstrated in the hangout, as well as what I have looked over myself, I think the Mary Poppins bag is ready to merge. :+1:

**Comment by rubyyot** [comment]
Awesome! Thank you sir :)

**Comment by rubyyot** [comment]
Yes!  Thank you @jcode89

**Comment by rubyyot** [comment]
I will initiate rebase soon.

**Comment by jcode89** [comment]
Initiate rebase! 👍🏽

Jonathan Colón

**Pull request merged**
