### PR TITLE
Dg create combat system

### PR DESCRIPTION
**Pull request by degustaf**

### CODE REVIEW

**Comment by jamalhansen** [comment]
Wow! A lot of good work in here

**Comment by phillipgray** [comment]
Uh oh. I think I made conflicts. Hmm. Let me know if you want to collaborate to squash them, @degustaf

**Comment by phillipgray** [comment]
Otherwise, the code looks good.

**Comment by phillipgray** [comment]
Looks solid. Tons of good work.
Resolved #75.
Resolved #50.
Resolved #51.

**Pull request merged**
