### PR TITLE
Removes item from room when picked up.

### PR DESCRIPTION
**Pull request by jcode89**
I have changed some code so *_key_* and *_gold_* will be removed when they are added to the bag. @jamalhansen try it out.

### CODE REVIEW

**Comment by jamalhansen** [comment]
This is much better, what do you think of it?   I like it.

**Comment by jcode89** [comment]
I love it. it is cleaner, the items come out of the board and there is now a function to take a key out of the bag when you enter a new level which I feel may be useful and can also be used to empty the bag completely upon entering new level.

**Comment by jamalhansen** [comment]
Sweet, merge away, good sir!

**Comment by jcode89** [comment]
Awesome!

**Pull request merged**
